config/routes.rb
Rails.application.routes.draw do

  resources :people
  resources :events
  get "/welcome/say_hellow"=>"welcome#say"
  get "welcome"=>"welcome#index"
  root "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :set_event, :only=>[ :show, :edit, :update, :destroy]
    #get /events/index
    #get /events
    def index
        @events=Event.page(params[:page]).per(10)
    end
    def new
        @event=Event.new
    end
    
    def create
        @event=Event.new(event_params)

       if @event.save
        flash[:notice]="新增成功"
        redirect_to :action=>:index
       else
        render :action=>:new
       end
    end
          
        
    
    def show
        
        @page_title=@event.name
    end
    
    def edit
       
    end
    
    def update
        
         if@event.update(event_params)
            flash[:notice]="新增成功" 
            redirect_to :action=>:show,:id=>@event
         else
            #redirect_to :action=>:edit,:id => @event
            render :action=>:edit
         end
    end
    

    def destroy
        
        @event.destroy
        flash[:alert]="新增成功"
        redirect_to :action=>:index 
    end
    
    private

    def set_event
        @event=Event.find(params[:id])
    end

    def event_params
        params.require(:event).permit(:name,:description)
    end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    #get/welcome/say_hellow
    def say
        
    end
    def index 
    
    end


    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
   <ul>
     <% @event.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
   </ul>
<% end %>

<p>
   <%= f.label :name,"Name"%>
   <%= f.text_field :name%>
<p>

<p>
   <%= f.label :description,"Description" %>
   <%= f.text_area :description%>
</p>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%= form_for @event ,:url=>{:controller=>'events',:action=>'update'} do |f| %>
<%= render :partial=>"form", :locals=>{:f=>f} %>
<%= f.submit "Update"%>
<% end %>

app/views/events/index.html.erb
<h1>Events list</h1>
<ul>
 
 <% @events.each do |event| %>
    <li>
      <%= event.name%>
      
      <%= event.description%>

      <%= link_to "show" ,:controller=>"events",:action=>'show',:id=>event%>
      <%= link_to "edit" ,:controller=>"events",:action=>'edit',:id=>event%>
      <%= link_to "delete",:controller=>'events',:action=>'destroy',:id=>event%>
    </li>
    
 <% end %>
 
</ul>
<%= paginate @events%>
<%= link_to 'new event', :controller=>'events', :action=>'new' %>

app/views/events/new.html.erb
<h1>create new event</h1>

<%= form_for @event, :url=>{:controller=>'events', :action=>'create'} do |f| %>
  <%= render :partial=>"form", :locals=>{:f=>f} %>
  <%= f.submit "Create"%>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name%></h1>
<%= @event.description%>
<p><%= link_to "back to index",:controller=>'events',:action=>'index'%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || 'DemoAgain' %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p style="color:green"><%= flash[:notice] %></p>
    <p style="color:red"><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.bio %></td>
        <td><%= person.birthday %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/welcome/index.html.erb
<p>Hola! It's <%= Time.now %></p>
<p><%= link_to 'Hellow', welcome_say_hellow_path%><p>

app/views/welcome/say.html.erb
<h1>hellow world</h1>
<%= 1+1%>